"""empty message

Revision ID: 537fc409132d
Revises: 
Create Date: 2024-03-13 17:06:17.155969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '537fc409132d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('type', sa.String(length=80), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('bedroom_no', sa.Integer(), nullable=True),
    sa.Column('bathroom_no', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property_info')
    # ### end Alembic commands ###
