"""empty message

Revision ID: c6987005c863
Revises: 537fc409132d
Create Date: 2024-03-16 23:38:54.166008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6987005c863'
down_revision = '537fc409132d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_info', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=2500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_info', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=2500),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True)

    # ### end Alembic commands ###
